#!/usr/bin/env python3
"""
Generate embeddings for dumps and chats for semantic search. Commits summary report to GitHub.
With full observability: timing, metrics, structured logging.
"""
import os
import sys
import json
from datetime import datetime, timezone

# Add parent to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from common import REPO_PATH, get_mongo_client, safe_git_commit_push
from observability import init_job, log_step, log_metric, complete_job, fail_job, timed_step

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY")
EMBEDDING_MODEL = os.environ.get("EMBEDDING_MODEL", "text-embedding-3-small")

def get_embedding(text):
    import requests
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
    }
    r = requests.post(
        "https://openrouter.ai/api/v1/embeddings",
        headers=headers,
        json={"model": EMBEDDING_MODEL, "input": text[:8000]},
        timeout=30
    )
    r.raise_for_status()
    return r.json()["data"][0]["embedding"]

def extract_text(doc):
    """Extract searchable text from a dump or chat document."""
    if "payload" in doc:
        payload = doc["payload"]
        if isinstance(payload, dict):
            # For audit dumps
            if "user" in payload:
                u = payload["user"]
                text = f"{u.get('login', '')} {u.get('name', '')} {u.get('bio', '')} "
                text += f"{payload.get('total', 0)} repos. "
                text += " ".join([r["name"] for r in payload.get("top_public_by_stars", [])[:10]])
                return text
            # For sync dumps
            if "events" in payload:
                return " ".join([e.get("type", "") for e in payload["events"][:20]])
        return json.dumps(payload)[:2000]
    return ""

def generate_embed_report(embedded_dumps, embedded_chats):
    """Generate markdown report from embedding run."""
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    md = f"# Embedding Report — {date_str}\n\n"
    md += f"**Generated:** {datetime.now(timezone.utc).isoformat()}Z\n\n"
    md += f"**Total new vectors:** {embedded_dumps + embedded_chats}\n\n"
    md += f"- **Dumps embedded:** {embedded_dumps}\n"
    md += f"- **Chats embedded:** {embedded_chats}\n\n"
    md += f"**Model:** {EMBEDDING_MODEL}\n\n"
    md += "---\n*Generated by automated embedding pipeline*\n"
    return md

def main():
    if not OPENROUTER_API_KEY:
        print("OPENROUTER_API_KEY not set", file=sys.stderr)
        sys.exit(1)
    
    run_id = init_job("embed-new")
    mongo = get_mongo_client()
    db = mongo["ai_agents"]
    dumps = db["dumps"]
    chats = db["chats"]
    embeddings = db["embeddings"]
    
    try:
        embedded_dumps = 0
        embedded_chats = 0
        api_calls = 0
        api_failures = 0
        
        # Embed unembedded dumps
        with timed_step("find_unembedded_dumps"):
            unembedded_dumps = list(dumps.find({
                "_id": {"$nin": [e["source_id"] for e in embeddings.find({"source_type": "dump"}, {"source_id": 1})]}
            }).limit(50))
        
        log_metric("unembedded_dumps_found", len(unembedded_dumps))
        
        for dump in unembedded_dumps:
            with timed_step(f"embed_dump_{str(dump['_id'])[:8]}"):
                text = extract_text(dump)
                if text.strip():
                    try:
                        vector = get_embedding(text)
                        embeddings.insert_one({
                            "source_type": "dump",
                            "source_id": dump["_id"],
                            "vector": vector,
                            "model": EMBEDDING_MODEL,
                            "text_preview": text[:200],
                            "created_at": datetime.now(timezone.utc),
                        })
                        embedded_dumps += 1
                        api_calls += 1
                    except Exception as e:
                        api_failures += 1
                        log_metric(f"embed_failure_dump_{str(dump['_id'])[:8]}", str(e))
        
        # Embed unembedded chats
        with timed_step("find_unembedded_chats"):
            unembedded_chats = list(chats.find({
                "_id": {"$nin": [e["source_id"] for e in embeddings.find({"source_type": "chat"}, {"source_id": 1})]}
            }).limit(50))
        
        log_metric("unembedded_chats_found", len(unembedded_chats))
        
        for chat in unembedded_chats:
            with timed_step(f"embed_chat_{str(chat['_id'])[:8]}"):
                text = chat.get("content", "")
                if text.strip():
                    try:
                        vector = get_embedding(text)
                        embeddings.insert_one({
                            "source_type": "chat",
                            "source_id": chat["_id"],
                            "vector": vector,
                            "model": EMBEDDING_MODEL,
                            "text_preview": text[:200],
                            "created_at": datetime.now(timezone.utc),
                        })
                        embedded_chats += 1
                        api_calls += 1
                    except Exception as e:
                        api_failures += 1
                        log_metric(f"embed_failure_chat_{str(chat['_id'])[:8]}", str(e))
        
        total_embedded = embedded_dumps + embedded_chats
        log_metric("total_embedded", total_embedded)
        log_metric("api_calls", api_calls)
        log_metric("api_failures", api_failures)
        
        # Generate and commit report if any embeddings were created
        if total_embedded > 0:
            with timed_step("generate_report"):
                md = generate_embed_report(embedded_dumps, embedded_chats)
                reports_dir = os.path.join(REPO_PATH, "reports")
                os.makedirs(reports_dir, exist_ok=True)
                date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
                report_file = os.path.join(reports_dir, f"{date_str}-embeddings.md")
                
                with open(report_file, "w") as f:
                    f.write(md)
            
            with timed_step("commit_push"):
                pushed = safe_git_commit_push(REPO_PATH, report_file, f"chore: embedding report {date_str}")
        else:
            pushed = None

        complete_job(
            status="completed" if pushed is not False else "completed_push_failed",
            embedded_dumps=embedded_dumps,
            embedded_chats=embedded_chats,
            total_embedded=total_embedded,
            api_calls=api_calls,
            api_failures=api_failures,
            report_pushed=pushed,
            report_file=report_file if total_embedded > 0 else None,
        )
        print(f"Embedding complete. {total_embedded} new vectors ({embedded_dumps} dumps, {embedded_chats} chats).")
        
    except Exception as e:
        fail_job(e)
        raise

if __name__ == "__main__":
    main()