#!/usr/bin/env python3
"""
Incremental GitHub sync. Fetches new commits, issues, PRs since last run. Commits report to GitHub.
With full observability: timing, metrics, structured logging.
"""
import os
import re
import sys
import subprocess
import requests
import pymongo
from datetime import datetime, timezone

# Add parent to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from observability import init_job, log_step, log_metric, complete_job, fail_job, timed_step, safe_git_commit_push

MONGO_URI = os.environ.get("MONGO_AI_URI", "mongodb+srv://Hermes:***@cluster0.rzg43g9.mongodb.net/?appName=Cluster0")
API = "https://api.github.com"
REPO_PATH = os.environ.get("REPO_PATH", "/opt/data/repo-analysis")

def get_github_token():
    # 1. Check environment variables first (for GitHub Actions, CI, etc.)
    for env_var in ["GITHUB_TOKEN", "GITHUB_PAT", "GH_TOKEN"]:
        token = os.environ.get(env_var)
        if token:
            return token
    
    # 2. Check ~/.env file
    env_path = os.path.expanduser("~/.env")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                if line.startswith("GITHUB_TOKEN="):
                    return line.strip().split("=", 1)[1].strip().strip('"')
    
    # 3. Check git credential store
    cred_path = os.path.expanduser("~/.git-credentials")
    if os.path.exists(cred_path):
        with open(cred_path) as f:
            for line in f:
                m = re.search(r'(github_pat_[^:@]+)@', line)
                if m:
                    return m.group(1)
    
    # 4. Try gh CLI
    try:
        return subprocess.check_output(["gh", "auth", "token"], text=True).strip()
    except:
        pass
    
    raise RuntimeError("No GitHub token found. Set GITHUB_TOKEN or GITHUB_PAT env var.")

def get_mongo_client():
    return pymongo.MongoClient(
        MONGO_URI,
        tlsAllowInvalidCertificates=True,
        serverSelectionTimeoutMS=30000
    )

def get_last_sync(mongo, repo_full_name):
    db = mongo["ai_agents"]
    sync = db["sync_state"]
    doc = sync.find_one({"repo": repo_full_name})
    return doc.get("last_sync") if doc else None

def update_last_sync(mongo, repo_full_name):
    db = mongo["ai_agents"]
    sync = db["sync_state"]
    sync.update_one(
        {"repo": repo_full_name},
        {"$set": {"last_sync": datetime.now(timezone.utc)}},
        upsert=True
    )

def fetch_repo_events(token, repo_full_name, since):
    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}
    params = {"per_page": 100}
    if since:
        params["since"] = since.isoformat() + "Z"
    
    events = []
    page = 1
    while True:
        r = requests.get(f"{API}/repos/{repo_full_name}/events", headers=headers, params={**params, "page": page}, timeout=30)
        r.raise_for_status()
        batch = r.json()
        if not batch:
            break
        events.extend(batch)
        page += 1
    return events

def generate_sync_report(repo_events):
    """Generate markdown report from sync run."""
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    md = f"# GitHub Sync Report — {date_str}\n\n"
    md += f"**Generated:** {datetime.now(timezone.utc).isoformat()}Z\n\n"
    
    total_events = sum(e["count"] for e in repo_events)
    md += f"**Repos synced:** {len(repo_events)}\n"
    md += f"**Total new events:** {total_events}\n\n"
    
    md += "## Per-Repo Breakdown\n\n"
    for e in repo_events:
        md += f"### {e['repo']}\n"
        md += f"- **Events:** {e['count']}\n"
        if e.get("event_types"):
            md += f"- **Types:** {e['event_types']}\n"
        md += "\n"
    
    md += "---\n*Generated by automated sync pipeline*\n"
    return md

def main():
    run_id = init_job("github-sync")
    token = get_github_token()
    mongo = get_mongo_client()
    db = mongo["ai_agents"]
    dumps = db["dumps"]
    repos_coll = db["repos"]
    
    try:
        # Get tracked repos from cache
        with timed_step("fetch_tracked_repos"):
            tracked = list(repos_coll.find({"private": False}, {"full_name": 1}))
        log_metric("repos_tracked", len(tracked))
        print(f"Syncing {len(tracked)} public repos...")
        
        total_events = 0
        repo_events = []
        
        for repo in tracked:
            full_name = repo["full_name"]
            with timed_step(f"sync_{full_name.replace('/', '_')}"):
                last_sync = get_last_sync(mongo, full_name)
                events = fetch_repo_events(token, full_name, last_sync)
                
                event_types = {}
                for e in events:
                    event_types[e.get("type", "unknown")] = event_types.get(e.get("type", "unknown"), 0) + 1
                
                if events:
                    dump_doc = {
                        "source": "github-sync",
                        "repo": full_name,
                        "payload": {"events": events, "count": len(events)},
                        "tags": ["sync", "events", "github"],
                        "created_at": datetime.now(timezone.utc),
                    }
                    dumps.insert_one(dump_doc)
                    total_events += len(events)
                    print(f"  {full_name}: {len(events)} new events")
                    
                    repo_events.append({
                        "repo": full_name,
                        "count": len(events),
                        "event_types": event_types,
                    })
                else:
                    repo_events.append({
                        "repo": full_name,
                        "count": 0,
                        "event_types": {},
                    })
                
                update_last_sync(mongo, full_name)
        
        log_metric("total_events_synced", total_events)
        log_metric("repos_with_events", sum(1 for e in repo_events if e["count"] > 0))
        
        # Generate and commit report
        if repo_events:
            with timed_step("generate_report"):
                md = generate_sync_report(repo_events)
                reports_dir = os.path.join(REPO_PATH, "reports")
                os.makedirs(reports_dir, exist_ok=True)
                date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
                report_file = os.path.join(reports_dir, f"{date_str}-sync.md")
                
                with open(report_file, "w") as f:
                    f.write(md)
            
            with timed_step("commit_push"):
                safe_git_commit_push(REPO_PATH, report_file, f"chore: sync report {date_str}")
        
        complete_job(
            status="completed",
            events_synced=total_events,
            repos_synced=len(repo_events),
            repos_with_events=sum(1 for e in repo_events if e["count"] > 0),
            report_file=report_file if repo_events else None,
        )
        print(f"Sync complete. {total_events} new events.")
        
    except Exception as e:
        fail_job(e)
        raise

if __name__ == "__main__":
    main()